server:
  port: 8082

spring:
  application:
    name: spring-ai-alibaba-audio-example-application
  ai:
    dashscope:
      api-key: sk-0be8343135b24c6e85cd5907f65fdb7c
logging:
  level:
    com.alibaba.cloud.ai.dashscope.protocol: DEBUG
    com.alibaba.cloud.ai.dashscope.api: DEBUG
    org.springframework.web.socket: DEBUG